[build]
outdir = "dist"
sourcemap = false
root = "src"
publicDir = "public"
base = "/deepseek-chat/"

[server]
host = true
port = 3010

[alias]
"@" = "./src"

[css]
preprocessorOptions.scss.api = "modern-compiler"
preprocessorOptions.scss.silenceDeprecations = ["legacy-js-api"]

[plugins]
vue = true
legacy.targets = ["chrome 52", "android 4.4"]
legacy.additionalLegacyPolyfills = ["regenerator-runtime/runtime"]
topLevelAwait = true
autoImport.imports = ["vue", "vue-router", "pinia"]
autoImport.dts = false
components.resolvers = ["ElementPlusResolver", "IconsResolver"]
icons.autoInstall = true
